[program:mifrog-worker]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/php/85/bin/php /www/wwwroot/PHPmifrog/artisan queue:work database --queue=default --sleep=1 --tries=2 --timeout=360
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
numprocs=3
redirect_stderr=true
stdout_logfile=/www/wwwlogs/mifrog-worker.log
stopwaitsecs=30
